/// Tiny hand-rolled localization. Tier-1 languages, icon-first UI.
class S {
  S._();

  static String locale = 'en';

  static const List<String> codes = <String>['en', 'es', 'fr', 'de', 'pt', 'it', 'ja'];

  static const Map<String, String> names = <String, String>{
    'en': 'English',
    'es': 'Español',
    'fr': 'Français',
    'de': 'Deutsch',
    'pt': 'Português',
    'it': 'Italiano',
    'ja': '日本語',
  };

  static String t(String key) =>
      _t[locale]?[key] ?? _t['en']?[key] ?? key;

  static const Map<String, Map<String, String>> _t = <String, Map<String, String>>{
    'en': <String, String>{
      'appTitle': 'Math Memory Planet',
      'choosePlanet': 'Choose a planet!',
      'level': 'Level',
      'stars': 'Stars',
      'streak': 'Day streak',
      'settings': 'Settings',
      'statsTitle': 'Parent stats',
      'parentGate': 'Grown-ups only!',
      'gateHint': 'Solve this to enter',
      'wellDone': 'Well done!',
      'next': 'Next',
      'replay': 'Replay',
      'home': 'Home',
      'language': 'Language',
      'sound': 'Sound',
      'resetProgress': 'Reset progress',
      'resetConfirm': 'Really reset? All stars will be lost.',
      'yesReset': 'Yes, reset',
      'cancel': 'Cancel',
      'privacy': 'Privacy policy',
      'about': 'About',
      'gamesPlayed': 'Games played',
      'timePlayed': 'Time played',
      'minutes': 'min',
      'mistakes': 'Mistakes',
      'moves': 'Moves',
      'rewards': 'Rewards',
      'cardBacks': 'Card backs',
      'themes': 'Themes',
      'confetti': 'Confetti',
      'unlockAt': 'Unlock at {n} stars',
      'selected': 'Selected',
      'select': 'Select',
      'watch': 'Watch...',
      'yourTurn': 'Your turn!',
      'find': 'Find',
      'target': 'Target',
      'tryAgain': 'Try again!',
      'ob_welcome': 'Welcome to',
      'ob_name': 'What should Nova call you? (optional)',
      'ob_skip': 'Skip',
      'ob_go': "Let's go!",
      'hi': 'Hi',
      'daily': 'Daily challenge',
      'combo': 'Combo',
      'ready': 'Ready?',
      'trophies': 'Trophies',
      'newBadge': 'New trophy',
      'b_first_win': 'First win',
      'b_ten_levels': '10 levels done',
      'b_perfect': 'Perfect level',
      'b_all_planets': 'All planets visited',
      'b_streak_7': '7-day streak',
      'b_stars_100': '100 stars',
      'b_planet_master': 'Planet master',
      'b_daily': 'Daily comet',
      'peek': 'Peek',
      'watchAgain': 'Watch again',
      'howTo': 'How to play',
      'play': 'Play!',
      'g_pairs_1': 'Tap a card',
      'g_pairs_2': 'Remember the number',
      'g_pairs_3': 'Find its pair!',
      'g_eqmatch_1': 'Tap a card',
      'g_eqmatch_2': 'Read the question',
      'g_eqmatch_3': 'Find the answer!',
      'g_sequence_1': 'Watch them glow',
      'g_sequence_2': 'Remember the order',
      'g_sequence_3': 'Tap them back!',
      'g_hidden_1': 'Look carefully',
      'g_hidden_2': 'Cards will hide',
      'g_hidden_3': 'Find the number!',
      'g_target_1': 'See the target',
      'g_target_2': 'Tap two cards',
      'g_target_3': 'They must add up!',
      'g_order_1': 'Remember the numbers',
      'g_order_2': 'Cards will hide',
      'g_order_3': 'Tap small to big!',
      'g_builder_1': 'Watch the equation',
      'g_builder_2': 'Remember it',
      'g_builder_3': 'Tap cards in order!',
      'mode_pairs': 'Number Pairs',
      'hint_pairs': 'Find the matching pairs!',
      'mode_eqmatch': 'Equation Match',
      'hint_eqmatch': 'Match the question to its answer!',
      'mode_sequence': 'Rocket Sequence',
      'hint_sequence': 'Watch, then repeat the order!',
      'mode_hidden': 'Hide and Seek',
      'hint_hidden': 'Remember, then find the number!',
      'mode_target': 'Target Sum',
      'hint_target': 'Make pairs that add up to the target!',
      'mode_order': 'Small to Big',
      'hint_order': 'Tap from smallest to biggest!',
      'mode_builder': 'Build the Equation',
      'hint_builder': 'Rebuild the equation in order!',
      'privacyBody': 'Math Memory Planet collects no personal data. No accounts, no ads, no internet, no analytics. All progress stays on this device only.',
    },
    'es': <String, String>{
      'appTitle': 'Math Memory Planet',
      'choosePlanet': '¡Elige un planeta!',
      'level': 'Nivel',
      'stars': 'Estrellas',
      'streak': 'Días seguidos',
      'settings': 'Ajustes',
      'statsTitle': 'Estadísticas',
      'parentGate': '¡Solo adultos!',
      'gateHint': 'Resuelve para entrar',
      'wellDone': '¡Muy bien!',
      'next': 'Siguiente',
      'replay': 'Otra vez',
      'home': 'Inicio',
      'language': 'Idioma',
      'sound': 'Sonido',
      'resetProgress': 'Borrar progreso',
      'resetConfirm': '¿Borrar todo? Se perderán las estrellas.',
      'yesReset': 'Sí, borrar',
      'cancel': 'Cancelar',
      'privacy': 'Privacidad',
      'about': 'Acerca de',
      'gamesPlayed': 'Partidas',
      'timePlayed': 'Tiempo de juego',
      'minutes': 'min',
      'mistakes': 'Errores',
      'moves': 'Movimientos',
      'rewards': 'Premios',
      'cardBacks': 'Reversos',
      'themes': 'Temas',
      'confetti': 'Confeti',
      'unlockAt': 'Desbloquea con {n} estrellas',
      'selected': 'Elegido',
      'select': 'Elegir',
      'watch': 'Mira...',
      'yourTurn': '¡Tu turno!',
      'find': 'Encuentra',
      'target': 'Meta',
      'tryAgain': '¡Inténtalo!',
      'ob_welcome': 'Bienvenido a',
      'ob_name': '¿Cómo te llamamos? (opcional)',
      'ob_skip': 'Saltar',
      'ob_go': '¡Vamos!',
      'hi': 'Hola',
      'daily': 'Reto diario',
      'combo': 'Combo',
      'ready': '¿Listo?',
      'trophies': 'Trofeos',
      'newBadge': 'Nuevo trofeo',
      'b_first_win': 'Primera victoria',
      'b_ten_levels': '10 niveles',
      'b_perfect': 'Nivel perfecto',
      'b_all_planets': 'Todos los planetas',
      'b_streak_7': '7 días seguidos',
      'b_stars_100': '100 estrellas',
      'b_planet_master': 'Planeta maestro',
      'b_daily': 'Cometa diario',
      'peek': 'Mirar',
      'watchAgain': 'Ver otra vez',
      'howTo': 'Cómo jugar',
      'play': '¡A jugar!',
      'g_pairs_1': 'Toca una carta',
      'g_pairs_2': 'Recuerda el número',
      'g_pairs_3': '¡Encuentra su pareja!',
      'g_eqmatch_1': 'Toca una carta',
      'g_eqmatch_2': 'Lee la pregunta',
      'g_eqmatch_3': '¡Encuentra la respuesta!',
      'g_sequence_1': 'Mira cómo brillan',
      'g_sequence_2': 'Recuerda el orden',
      'g_sequence_3': '¡Tócalos igual!',
      'g_hidden_1': 'Mira bien',
      'g_hidden_2': 'Las cartas se esconden',
      'g_hidden_3': '¡Encuentra el número!',
      'g_target_1': 'Mira la meta',
      'g_target_2': 'Toca dos cartas',
      'g_target_3': '¡Deben sumar la meta!',
      'g_order_1': 'Recuerda los números',
      'g_order_2': 'Las cartas se esconden',
      'g_order_3': '¡Toca de menor a mayor!',
      'g_builder_1': 'Mira la operación',
      'g_builder_2': 'Recuérdala',
      'g_builder_3': '¡Toca las cartas en orden!',
      'mode_pairs': 'Parejas',
      'hint_pairs': '¡Encuentra las parejas!',
      'mode_eqmatch': 'Operaciones',
      'hint_eqmatch': '¡Une la pregunta con su respuesta!',
      'mode_sequence': 'Secuencia Cohete',
      'hint_sequence': '¡Mira y repite el orden!',
      'mode_hidden': 'Escondite',
      'hint_hidden': '¡Recuerda y encuentra el número!',
      'mode_target': 'Suma Meta',
      'hint_target': '¡Haz parejas que sumen la meta!',
      'mode_order': 'De Menor a Mayor',
      'hint_order': '¡Toca del menor al mayor!',
      'mode_builder': 'Arma la Ecuación',
      'hint_builder': '¡Arma la ecuación en orden!',
      'privacyBody': 'Math Memory Planet no recoge datos personales. Sin cuentas, sin anuncios, sin internet. Todo el progreso queda en este dispositivo.',
    },
    'fr': <String, String>{
      'appTitle': 'Math Memory Planet',
      'choosePlanet': 'Choisis une planète !',
      'level': 'Niveau',
      'stars': 'Étoiles',
      'streak': 'Jours de suite',
      'settings': 'Réglages',
      'statsTitle': 'Statistiques',
      'parentGate': 'Réservé aux adultes !',
      'gateHint': 'Résous pour entrer',
      'wellDone': 'Bravo !',
      'next': 'Suivant',
      'replay': 'Rejouer',
      'home': 'Accueil',
      'language': 'Langue',
      'sound': 'Son',
      'resetProgress': 'Tout effacer',
      'resetConfirm': 'Tout effacer ? Les étoiles seront perdues.',
      'yesReset': 'Oui, effacer',
      'cancel': 'Annuler',
      'privacy': 'Confidentialité',
      'about': 'À propos',
      'gamesPlayed': 'Parties',
      'timePlayed': 'Temps de jeu',
      'minutes': 'min',
      'mistakes': 'Erreurs',
      'moves': 'Coups',
      'rewards': 'Récompenses',
      'cardBacks': 'Dos de cartes',
      'themes': 'Thèmes',
      'confetti': 'Confettis',
      'unlockAt': 'Débloque à {n} étoiles',
      'selected': 'Choisi',
      'select': 'Choisir',
      'watch': 'Regarde...',
      'yourTurn': 'À toi !',
      'find': 'Trouve',
      'target': 'Cible',
      'tryAgain': 'Réessaie !',
      'ob_welcome': 'Bienvenue sur',
      'ob_name': 'Comment tu t’appelles ? (optionnel)',
      'ob_skip': 'Passer',
      'ob_go': 'C’est parti !',
      'hi': 'Salut',
      'daily': 'Défi du jour',
      'combo': 'Combo',
      'ready': 'Prêt ?',
      'trophies': 'Trophées',
      'newBadge': 'Nouveau trophée',
      'b_first_win': 'Première victoire',
      'b_ten_levels': '10 niveaux',
      'b_perfect': 'Niveau parfait',
      'b_all_planets': 'Toutes les planètes',
      'b_streak_7': '7 jours de suite',
      'b_stars_100': '100 étoiles',
      'b_planet_master': 'Maître de la planète',
      'b_daily': 'Comète du jour',
      'peek': 'Coup d’œil',
      'watchAgain': 'Revoir',
      'howTo': 'Comment jouer',
      'play': 'Jouer !',
      'g_pairs_1': 'Touche une carte',
      'g_pairs_2': 'Retiens le nombre',
      'g_pairs_3': 'Trouve sa paire !',
      'g_eqmatch_1': 'Touche une carte',
      'g_eqmatch_2': 'Lis la question',
      'g_eqmatch_3': 'Trouve la réponse !',
      'g_sequence_1': 'Regarde-les briller',
      'g_sequence_2': 'Retiens l’ordre',
      'g_sequence_3': 'Rejoue l’ordre !',
      'g_hidden_1': 'Regarde bien',
      'g_hidden_2': 'Les cartes se cachent',
      'g_hidden_3': 'Trouve le nombre !',
      'g_target_1': 'Regarde la cible',
      'g_target_2': 'Touche deux cartes',
      'g_target_3': 'Elles doivent faire la cible !',
      'g_order_1': 'Retiens les nombres',
      'g_order_2': 'Les cartes se cachent',
      'g_order_3': 'Touche du petit au grand !',
      'g_builder_1': 'Regarde l’opération',
      'g_builder_2': 'Retiens-la',
      'g_builder_3': 'Touche les cartes dans l’ordre !',
      'mode_pairs': 'Paires',
      'hint_pairs': 'Trouve les paires !',
      'mode_eqmatch': 'Opérations',
      'hint_eqmatch': 'Relie la question à sa réponse !',
      'mode_sequence': 'Séquence Fusée',
      'hint_sequence': 'Regarde, puis répète l’ordre !',
      'mode_hidden': 'Cache-cache',
      'hint_hidden': 'Mémorise, puis trouve le nombre !',
      'mode_target': 'Somme Cible',
      'hint_target': 'Forme des paires qui font la cible !',
      'mode_order': 'Du Petit au Grand',
      'hint_order': 'Touche du plus petit au plus grand !',
      'mode_builder': 'Construis l’Opération',
      'hint_builder': 'Reconstruis l’opération dans l’ordre !',
      'privacyBody': 'Math Memory Planet ne collecte aucune donnée. Pas de comptes, pas de pub, pas d’internet. Toute la progression reste sur cet appareil.',
    },
    'de': <String, String>{
      'appTitle': 'Math Memory Planet',
      'choosePlanet': 'Wähle einen Planeten!',
      'level': 'Level',
      'stars': 'Sterne',
      'streak': 'Tage-Serie',
      'settings': 'Einstellungen',
      'statsTitle': 'Eltern-Statistik',
      'parentGate': 'Nur für Erwachsene!',
      'gateHint': 'Löse die Aufgabe',
      'wellDone': 'Super gemacht!',
      'next': 'Weiter',
      'replay': 'Nochmal',
      'home': 'Start',
      'language': 'Sprache',
      'sound': 'Ton',
      'resetProgress': 'Zurücksetzen',
      'resetConfirm': 'Wirklich löschen? Alle Sterne gehen verloren.',
      'yesReset': 'Ja, löschen',
      'cancel': 'Abbrechen',
      'privacy': 'Datenschutz',
      'about': 'Über',
      'gamesPlayed': 'Spiele',
      'timePlayed': 'Spielzeit',
      'minutes': 'Min.',
      'mistakes': 'Fehler',
      'moves': 'Züge',
      'rewards': 'Belohnungen',
      'cardBacks': 'Kartenrücken',
      'themes': 'Designs',
      'confetti': 'Konfetti',
      'unlockAt': 'Ab {n} Sternen',
      'selected': 'Gewählt',
      'select': 'Wählen',
      'watch': 'Schau...',
      'yourTurn': 'Du bist dran!',
      'find': 'Finde',
      'target': 'Ziel',
      'tryAgain': 'Nochmal!',
      'ob_welcome': 'Willkommen bei',
      'ob_name': 'Wie sollen wir dich nennen? (optional)',
      'ob_skip': 'Überspringen',
      'ob_go': 'Los geht’s!',
      'hi': 'Hallo',
      'daily': 'Tages-Challenge',
      'combo': 'Combo',
      'ready': 'Bereit?',
      'trophies': 'Trophäen',
      'newBadge': 'Neue Trophäe',
      'b_first_win': 'Erster Sieg',
      'b_ten_levels': '10 Level geschafft',
      'b_perfect': 'Perfektes Level',
      'b_all_planets': 'Alle Planeten besucht',
      'b_streak_7': '7-Tage-Serie',
      'b_stars_100': '100 Sterne',
      'b_planet_master': 'Planeten-Meister',
      'b_daily': 'Tages-Komet',
      'peek': 'Spicken',
      'watchAgain': 'Nochmal sehen',
      'howTo': 'So geht’s',
      'play': 'Spielen!',
      'g_pairs_1': 'Tippe eine Karte',
      'g_pairs_2': 'Merk dir die Zahl',
      'g_pairs_3': 'Finde ihr Paar!',
      'g_eqmatch_1': 'Tippe eine Karte',
      'g_eqmatch_2': 'Lies die Aufgabe',
      'g_eqmatch_3': 'Finde die Antwort!',
      'g_sequence_1': 'Schau sie leuchten',
      'g_sequence_2': 'Merk dir die Reihenfolge',
      'g_sequence_3': 'Tippe sie nach!',
      'g_hidden_1': 'Schau genau hin',
      'g_hidden_2': 'Karten drehen sich um',
      'g_hidden_3': 'Finde die Zahl!',
      'g_target_1': 'Schau aufs Ziel',
      'g_target_2': 'Tippe zwei Karten',
      'g_target_3': 'Zusammen ergeben sie das Ziel!',
      'g_order_1': 'Merk dir die Zahlen',
      'g_order_2': 'Karten drehen sich um',
      'g_order_3': 'Tippe von klein nach groß!',
      'g_builder_1': 'Schau die Rechnung',
      'g_builder_2': 'Merk sie dir',
      'g_builder_3': 'Tippe die Karten der Reihe nach!',
      'mode_pairs': 'Zahlenpaare',
      'hint_pairs': 'Finde die Paare!',
      'mode_eqmatch': 'Rechen-Match',
      'hint_eqmatch': 'Verbinde Aufgabe und Antwort!',
      'mode_sequence': 'Raketen-Reihe',
      'hint_sequence': 'Schau zu und wiederhole die Reihenfolge!',
      'mode_hidden': 'Verstecken',
      'hint_hidden': 'Merken, dann die Zahl finden!',
      'mode_target': 'Zielsumme',
      'hint_target': 'Bilde Paare, die das Ziel ergeben!',
      'mode_order': 'Klein nach Groß',
      'hint_order': 'Tippe von klein nach groß!',
      'mode_builder': 'Baue die Rechnung',
      'hint_builder': 'Baue die Rechnung in der richtigen Reihenfolge!',
      'privacyBody': 'Math Memory Planet sammelt keine Daten. Keine Konten, keine Werbung, kein Internet. Der gesamte Fortschritt bleibt auf diesem Gerät.',
    },
    'pt': <String, String>{
      'appTitle': 'Math Memory Planet',
      'choosePlanet': 'Escolhe um planeta!',
      'level': 'Nível',
      'stars': 'Estrelas',
      'streak': 'Dias seguidos',
      'settings': 'Definições',
      'statsTitle': 'Estatísticas',
      'parentGate': 'Só adultos!',
      'gateHint': 'Resolve para entrar',
      'wellDone': 'Muito bem!',
      'next': 'Seguinte',
      'replay': 'Outra vez',
      'home': 'Início',
      'language': 'Idioma',
      'sound': 'Som',
      'resetProgress': 'Apagar progresso',
      'resetConfirm': 'Apagar tudo? As estrelas vão-se perder.',
      'yesReset': 'Sim, apagar',
      'cancel': 'Cancelar',
      'privacy': 'Privacidade',
      'about': 'Sobre',
      'gamesPlayed': 'Jogos',
      'timePlayed': 'Tempo de jogo',
      'minutes': 'min',
      'mistakes': 'Erros',
      'moves': 'Jogadas',
      'rewards': 'Prémios',
      'cardBacks': 'Versos',
      'themes': 'Temas',
      'confetti': 'Confetis',
      'unlockAt': 'Desbloqueia com {n} estrelas',
      'selected': 'Escolhido',
      'select': 'Escolher',
      'watch': 'Olha...',
      'yourTurn': 'A tua vez!',
      'find': 'Encontra',
      'target': 'Meta',
      'tryAgain': 'Tenta outra vez!',
      'ob_welcome': 'Bem-vindo a',
      'ob_name': 'Como te chamamos? (opcional)',
      'ob_skip': 'Saltar',
      'ob_go': 'Vamos lá!',
      'hi': 'Olá',
      'daily': 'Desafio diário',
      'combo': 'Combo',
      'ready': 'Preparado?',
      'trophies': 'Troféus',
      'newBadge': 'Novo troféu',
      'b_first_win': 'Primeira vitória',
      'b_ten_levels': '10 níveis',
      'b_perfect': 'Nível perfeito',
      'b_all_planets': 'Todos os planetas',
      'b_streak_7': '7 dias seguidos',
      'b_stars_100': '100 estrelas',
      'b_planet_master': 'Mestre do planeta',
      'b_daily': 'Cometa diário',
      'peek': 'Espiar',
      'watchAgain': 'Ver outra vez',
      'howTo': 'Como jogar',
      'play': 'Jogar!',
      'g_pairs_1': 'Toca numa carta',
      'g_pairs_2': 'Memoriza o número',
      'g_pairs_3': 'Encontra o par!',
      'g_eqmatch_1': 'Toca numa carta',
      'g_eqmatch_2': 'Lê a pergunta',
      'g_eqmatch_3': 'Encontra a resposta!',
      'g_sequence_1': 'Vê-os brilhar',
      'g_sequence_2': 'Memoriza a ordem',
      'g_sequence_3': 'Toca na mesma ordem!',
      'g_hidden_1': 'Olha bem',
      'g_hidden_2': 'As cartas escondem-se',
      'g_hidden_3': 'Encontra o número!',
      'g_target_1': 'Vê a meta',
      'g_target_2': 'Toca em duas cartas',
      'g_target_3': 'Têm de somar a meta!',
      'g_order_1': 'Memoriza os números',
      'g_order_2': 'As cartas escondem-se',
      'g_order_3': 'Toca do menor ao maior!',
      'g_builder_1': 'Vê a conta',
      'g_builder_2': 'Memoriza-a',
      'g_builder_3': 'Toca nas cartas por ordem!',
      'mode_pairs': 'Pares',
      'hint_pairs': 'Encontra os pares!',
      'mode_eqmatch': 'Contas',
      'hint_eqmatch': 'Liga a pergunta à resposta!',
      'mode_sequence': 'Sequência Foguete',
      'hint_sequence': 'Olha e repete a ordem!',
      'mode_hidden': 'Escondidas',
      'hint_hidden': 'Memoriza e encontra o número!',
      'mode_target': 'Soma Meta',
      'hint_target': 'Faz pares que somem a meta!',
      'mode_order': 'Do Menor ao Maior',
      'hint_order': 'Toca do menor ao maior!',
      'mode_builder': 'Monta a Conta',
      'hint_builder': 'Monta a conta pela ordem certa!',
      'privacyBody': 'Math Memory Planet não recolhe dados. Sem contas, sem anúncios, sem internet. Todo o progresso fica neste dispositivo.',
    },
    'it': <String, String>{
      'appTitle': 'Math Memory Planet',
      'choosePlanet': 'Scegli un pianeta!',
      'level': 'Livello',
      'stars': 'Stelle',
      'streak': 'Giorni di fila',
      'settings': 'Impostazioni',
      'statsTitle': 'Statistiche',
      'parentGate': 'Solo adulti!',
      'gateHint': 'Risolvi per entrare',
      'wellDone': 'Bravissimo!',
      'next': 'Avanti',
      'replay': 'Rigioca',
      'home': 'Home',
      'language': 'Lingua',
      'sound': 'Suono',
      'resetProgress': 'Azzera tutto',
      'resetConfirm': 'Azzerare davvero? Le stelle andranno perse.',
      'yesReset': 'Sì, azzera',
      'cancel': 'Annulla',
      'privacy': 'Privacy',
      'about': 'Info',
      'gamesPlayed': 'Partite',
      'timePlayed': 'Tempo di gioco',
      'minutes': 'min',
      'mistakes': 'Errori',
      'moves': 'Mosse',
      'rewards': 'Premi',
      'cardBacks': 'Retro carte',
      'themes': 'Temi',
      'confetti': 'Coriandoli',
      'unlockAt': 'Sblocca a {n} stelle',
      'selected': 'Scelto',
      'select': 'Scegli',
      'watch': 'Guarda...',
      'yourTurn': 'Tocca a te!',
      'find': 'Trova',
      'target': 'Obiettivo',
      'tryAgain': 'Riprova!',
      'ob_welcome': 'Benvenuto su',
      'ob_name': 'Come ti chiamiamo? (facoltativo)',
      'ob_skip': 'Salta',
      'ob_go': 'Andiamo!',
      'hi': 'Ciao',
      'daily': 'Sfida del giorno',
      'combo': 'Combo',
      'ready': 'Pronto?',
      'trophies': 'Trofei',
      'newBadge': 'Nuovo trofeo',
      'b_first_win': 'Prima vittoria',
      'b_ten_levels': '10 livelli',
      'b_perfect': 'Livello perfetto',
      'b_all_planets': 'Tutti i pianeti',
      'b_streak_7': '7 giorni di fila',
      'b_stars_100': '100 stelle',
      'b_planet_master': 'Maestro del pianeta',
      'b_daily': 'Cometa del giorno',
      'peek': 'Sbircia',
      'watchAgain': 'Rivedi',
      'howTo': 'Come si gioca',
      'play': 'Gioca!',
      'g_pairs_1': 'Tocca una carta',
      'g_pairs_2': 'Ricorda il numero',
      'g_pairs_3': 'Trova la coppia!',
      'g_eqmatch_1': 'Tocca una carta',
      'g_eqmatch_2': 'Leggi la domanda',
      'g_eqmatch_3': 'Trova la risposta!',
      'g_sequence_1': 'Guardali brillare',
      'g_sequence_2': 'Ricorda l’ordine',
      'g_sequence_3': 'Toccali nello stesso ordine!',
      'g_hidden_1': 'Guarda bene',
      'g_hidden_2': 'Le carte si nascondono',
      'g_hidden_3': 'Trova il numero!',
      'g_target_1': 'Guarda il target',
      'g_target_2': 'Tocca due carte',
      'g_target_3': 'Devono fare la somma!',
      'g_order_1': 'Ricorda i numeri',
      'g_order_2': 'Le carte si nascondono',
      'g_order_3': 'Tocca dal più piccolo!',
      'g_builder_1': 'Guarda l’operazione',
      'g_builder_2': 'Ricordala',
      'g_builder_3': 'Tocca le carte in ordine!',
      'mode_pairs': 'Coppie',
      'hint_pairs': 'Trova le coppie!',
      'mode_eqmatch': 'Operazioni',
      'hint_eqmatch': 'Collega la domanda alla risposta!',
      'mode_sequence': 'Sequenza Razzo',
      'hint_sequence': 'Guarda e ripeti l’ordine!',
      'mode_hidden': 'Nascondino',
      'hint_hidden': 'Ricorda e trova il numero!',
      'mode_target': 'Somma Target',
      'hint_target': 'Forma coppie che fanno il target!',
      'mode_order': 'Dal Piccolo al Grande',
      'hint_order': 'Tocca dal più piccolo al più grande!',
      'mode_builder': 'Costruisci l’Operazione',
      'hint_builder': 'Ricostruisci l’operazione in ordine!',
      'privacyBody': 'Math Memory Planet non raccoglie dati. Nessun account, nessuna pubblicità, nessun internet. Tutti i progressi restano su questo dispositivo.',
    },
    'ja': <String, String>{
      'appTitle': 'すうじメモリープラネット',
      'choosePlanet': 'ほしをえらんでね！',
      'level': 'レベル',
      'stars': 'ほし',
      'streak': 'れんぞくにっすう',
      'settings': 'せってい',
      'statsTitle': 'おうちのかたへ',
      'parentGate': 'おとなのひとだけ！',
      'gateHint': 'もんだいをといてね',
      'wellDone': 'よくできたね！',
      'next': 'つぎへ',
      'replay': 'もういっかい',
      'home': 'ホーム',
      'language': 'ことば',
      'sound': 'おと',
      'resetProgress': 'リセット',
      'resetConfirm': 'ほんとうにリセットする？ほしがきえるよ。',
      'yesReset': 'リセットする',
      'cancel': 'キャンセル',
      'privacy': 'プライバシー',
      'about': 'このアプリについて',
      'gamesPlayed': 'あそんだかいすう',
      'timePlayed': 'あそんだじかん',
      'minutes': 'ふん',
      'mistakes': 'まちがい',
      'moves': 'てすう',
      'rewards': 'ごほうび',
      'cardBacks': 'カードのうらがわ',
      'themes': 'テーマ',
      'confetti': 'こんふぇってぃ',
      'unlockAt': 'ほし{n}こでかいほう',
      'selected': 'えらんだもの',
      'select': 'えらぶ',
      'watch': 'よく見て...',
      'yourTurn': 'きみのばん！',
      'find': 'さがして',
      'target': 'ターゲット',
      'tryAgain': 'もういちど！',
      'ob_welcome': 'ようこそ',
      'ob_name': 'なまえをおしえてね（あとでもOK）',
      'ob_skip': 'スキップ',
      'ob_go': 'スタート！',
      'hi': 'こんにちは',
      'daily': 'まいにちチャレンジ',
      'combo': 'コンボ',
      'ready': 'レディ？',
      'trophies': 'トロフィー',
      'newBadge': 'あたらしいトロフィー',
      'b_first_win': 'はじめてのかち',
      'b_ten_levels': '10レベルクリア',
      'b_perfect': 'パーフェクト',
      'b_all_planets': 'すべてのほしへ',
      'b_streak_7': '7にちれんぞく',
      'b_stars_100': '100このほし',
      'b_planet_master': 'プラネットマスター',
      'b_daily': 'まいにちコメット',
      'peek': 'チラ見',
      'watchAgain': 'もういっかい見る',
      'howTo': 'あそびかた',
      'play': 'あそぶ！',
      'g_pairs_1': 'カードをタップ',
      'g_pairs_2': 'かずをおぼえて',
      'g_pairs_3': 'ペアをみつけてね！',
      'g_eqmatch_1': 'カードをタップ',
      'g_eqmatch_2': 'もんだいをよんで',
      'g_eqmatch_3': 'こたえをみつけてね！',
      'g_sequence_1': 'ひかるのを見て',
      'g_sequence_2': 'じゅんばんをおぼえて',
      'g_sequence_3': 'おなじじゅんでタップ！',
      'g_hidden_1': 'よく見て',
      'g_hidden_2': 'カードがかくれるよ',
      'g_hidden_3': 'かずをさがしてね！',
      'g_target_1': 'ターゲットを見て',
      'g_target_2': '2まいタップ',
      'g_target_3': 'たしてターゲットにしよう！',
      'g_order_1': 'かずをおぼえて',
      'g_order_2': 'カードがかくれるよ',
      'g_order_3': 'ちいさいじゅんにタップ！',
      'g_builder_1': 'しきを見て',
      'g_builder_2': 'おぼえて',
      'g_builder_3': 'じゅんばんどおりタップ！',
      'mode_pairs': 'すうじペア',
      'hint_pairs': 'ペアをみつけてね！',
      'mode_eqmatch': 'けいさんマッチ',
      'hint_eqmatch': 'もんだいとこたえをつなげてね！',
      'mode_sequence': 'ロケットれんぞく',
      'hint_sequence': '見て、じゅんばんにおぼえてね！',
      'mode_hidden': 'かくれんぼ',
      'hint_hidden': 'おぼえて、かずをさがしてね！',
      'mode_target': 'ターゲットのかず',
      'hint_target': 'たしてターゲットになるペアをつくってね！',
      'mode_order': 'ちいさいじゅん',
      'hint_order': 'ちいさいじゅんにおしてね！',
      'mode_builder': 'しきをつくろう',
      'hint_builder': 'しきをじゅんばんどおりにしてね！',
      'privacyBody': 'Math Memory Planetはデータをあつめません。アカウントなし、広告なし、インターネットなし。進行はすべてこの端末に保存されます。',
    },
  };
}
